name: monggo_pinarak_cms
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  cloud_firestore: ^2.5.3
  firebase_core: ^1.6.0
  firebase_analytics: ^8.3.2
  firebase_storage: ^10.0.3
  permission_handler: ^8.1.6
  cached_network_image: ^3.1.0
  image_picker: ^0.8.4+2
  image_cropper: ^1.4.1
  pointycastle: ^3.3.4
  shared_preferences: ^2.0.8
  pull_to_refresh: ^2.0.0
  intl: ^0.17.0
  fl_chart: ^0.40.0
  firebase_auth: ^3.1.1
  nav_router:
    git:
      url: https://github.com/dwikyhardi/nav_router
  date_util:
    git:
      url: https://github.com/dwikyhardi/Date-Utility
  dio: ^4.0.0
  pretty_dio_logger: ^1.1.1
  retrofit: ^2.0.1
  build_runner: ^2.1.2
  json_serializable: ^5.0.2
  retrofit_generator: ^2.0.1+1
  url_launcher: ^6.0.10
  flutter_bloc: ^7.3.0
  rxdart: ^0.27.2
  fluttertoast: ^8.0.8

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

flutter_icons:
  ios: true
  android: true
  remove_alpha_ios: true
  image_path: "assets/icons/ic_logo.png"

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/icons/
